-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm2mfL3PlE5jBdOnxPfNr3oqqXAANTftyZ1yS4SA3iKCgCgYIKoZIzj0DAQehRANCAAQdusvLmsTzUKPxogQRaEEdReLT/43l0Tl/mogZsucgCHuf7YCljY2mlxYfwNot9oarHP8mp2ZYblaw3Okpe6Jd
-----END PRIVATE KEY-----